name: Build and upload docker image.

on:

  push:
    branches:
      - master

jobs:
  build-image:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo.
        uses: actions/checkout@v2

      - name: Login into docker hub.
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username gulis1 --password-stdin

      - name: Build image.
        run: docker image build --tag gulis1/botwebo2:latest -f ./docker/Dockerfile .

      - name: Upload image.
        run: docker image push gulis1/botwebo2:latest

